name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Installation de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # Déploiement sur Vercel avec confirmation automatique
      - name: Deploy to Vercel
        run: |
          npx vercel@25.2.0 --token ${{ secrets.VERCEL_TOKEN }} --name "ai-images-analysis" --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

          